sudo: required
services:
  - docker
language: python
python:
  - "3.5"

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - "pip install -r ./build/requirements/requirements.txt"
  - "pip install Flask-Testing coverage pep8 rednose"
  # nose is already installed by default.
  - "docker-compose -f ./build/testing.yml up -d"
cache:
  - pip
script:
  - "pep8 ."
  - "python manage.py test"
  - "docker-compose -f ./build/testing.yml run --rm sipa_testing"
